<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="griffon.exceptions.InstanceMethodInvocationExceptionSpec" tests="3" skipped="0" failures="0" errors="0" timestamp="2017-04-28T15:17:39" hostname="testing-docker-71ed3c1d-8272-422d-a8a2-10bd4b41ce0f" time="0.017">
  <properties/>
  <testcase name="Exception should have proper formatted message (1)[0]" classname="griffon.exceptions.InstanceMethodInvocationExceptionSpec" time="0.008"/>
  <testcase name="Exception should have proper formatted message (1)[1]" classname="griffon.exceptions.InstanceMethodInvocationExceptionSpec" time="0.0"/>
  <testcase name="Exception should have proper formatted message (2)[0]" classname="griffon.exceptions.InstanceMethodInvocationExceptionSpec" time="0.008"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
