<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="griffon.exceptions.InstanceMethodInvocationExceptionSpec" tests="3" skipped="0" failures="0" errors="0" timestamp="2017-05-04T09:04:56" hostname="testing-docker-ace0605b-7337-48a1-8fdb-4d5d4cfd489f" time="0.015">
  <properties/>
  <testcase name="Exception should have proper formatted message (1)[0]" classname="griffon.exceptions.InstanceMethodInvocationExceptionSpec" time="0.005"/>
  <testcase name="Exception should have proper formatted message (1)[1]" classname="griffon.exceptions.InstanceMethodInvocationExceptionSpec" time="0.0"/>
  <testcase name="Exception should have proper formatted message (2)[0]" classname="griffon.exceptions.InstanceMethodInvocationExceptionSpec" time="0.009"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
